config/routes.rb
Rails.application.routes.draw do
  resources :twitters do
    member do
      get 'preview'
    end
    
    collection do
      get 'search'
    end
    
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "twitters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitter.rb
class Twitter < ApplicationRecord
  include PgSearch::Model 
  
  pg_search_scope :search_full_text, 
  against: {
    username: 'A',
    id: 'B'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #Pagy::DEFAULT[:limit] = 10
  include Pagy::Backend
  allow_browser versions: :modern
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: %i[ show edit update destroy ]

  # GET /twitters or /twitters.json
  
  def index
    @pagy, @twitters = pagy(Twitter.order(created_at: :desc))

    if params[:query_text].present?
      @twitters = @twitters.search_full_text(params[:query_text])
    end
  end

  # GET /twitters/1 or /twitters/1.json
  def show
  end

  # GET /twitters/new
  def new
    @twitter = Twitter.new
  end

  # GET /twitters/1/edit
  def edit
  end

  def preview
  end

  def search
  end

  # POST /twitters or /twitters.json
  def create
    @twitter = Twitter.new(twitter_params)

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to @twitter, notice: "Twitter was successfully created." }
        format.json { render :show, status: :created, location: @twitter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitters/1 or /twitters/1.json
  def update
    respond_to do |format|
      if @twitter.update(twitter_params)
        format.html { redirect_to @twitter, notice: "Twitter was successfully updated." }
        format.json { render :show, status: :ok, location: @twitter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitters/1 or /twitters/1.json
  def destroy
    @twitter.destroy!

    respond_to do |format|
      format.html { redirect_to twitters_path, status: :see_other, notice: "Twitter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter
      @twitter = Twitter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twitter_params
      params.require(:twitter).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Clontwitter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Twitter</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "New twitter", new_twitter_path, class:"nav-link active" %>
            </li>
          </ul>
          <%= form_with url: twitters_path, method: :get do |form|%>
            <div class="d-flex flex-row">
              
              <%= form.text_field :query_text, placeholder: t('Query text'), value: params[:query_text], class:"form-control me-2"%>
              <%= button_to "Search", @twitter, method: :search, class:"btn btn-outline-success", data: {confirm: 'Esta seguro?'} %>
              
            </div>
          <%end%>
          
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: twitter) do |form| %>
  <% if twitter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twitter.errors.count, "error") %> prohibited this twitter from being saved:</h2>

      <ul>
        <% twitter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/twitters/_twitter.html.erb
<div id="<%= dom_id twitter %>">
  <p>
    <strong>Description:</strong>
    <%= twitter.description %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= twitter.username %>
  </p>

</div>

app/views/twitters/edit.html.erb
<% content_for :title, "Editing twitter" %>

<h1>Editing twitter</h1>

<%= render "form", twitter: @twitter %>

<br>

<div >
  <%= link_to "Show this twitter", @twitter, class:"btn btn-dark" %> |
  <%= link_to "Back to twitters", twitters_path, class:"btn btn-dark" %>
</div>

app/views/twitters/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Twitters" %>

<h1>
  Twitters:
  <%=@twitters.count%>
  /
  <%=Twitter.count%>
</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Tweet</th>
      <th scope="col">Username</th>
      <th scope="col">Create</th>
      
    </tr>
  </thead>
  <tbody>
    <div id="twitters">
      <% @twitters.each do |twitter| %>
        
        <tr>
          <th><%= twitter.id%></th>
          <td><%= twitter.description%></td>
          <td><%= twitter.username%></td>
          <td><%= twitter.created_at%></td>
          <td><%= link_to "Show", twitter, class:"btn btn-dark" %></td>
          <td><%= link_to "Edit", edit_twitter_path(twitter), class:"btn btn-dark" %></td>
          <td><%= button_to "Destroy", @twitter, method: :delete, class:"btn btn-danger", data: {confirm: 'Esta seguro?'} %></td>
        </tr>
      <% end %>
    </div>
    
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/twitters/new.html.erb
<% content_for :title, "New twitter" %>

<h1>New twitter</h1>

<%= render "form", twitter: @twitter %>

<br>

<div>
  <%= link_to "Back to twitters", twitters_path, class:"btn btn-dark" %>
</div>

app/views/twitters/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Tweet</h5>
    <%= render @twitter %>
    <%= link_to "Edit this twitter", edit_twitter_path(@twitter), class:"card-link" %>
    <%= link_to "Back to twitters", twitters_path, class:"card-link" %>
  </div>
</div>


<div class = "pt-3">
  <%= button_to "Destroy", @twitter, method: :delete, class:"btn btn-danger" %>
</div>